### ISSUE TITLE
how can i use setinterval function in react

### ISSUE THREAD

**Issue by Oleksandr0811** [Kus-lab/casino-admin-platform#1]
Please help me with sample code

**Comment by webgently** [comment]
Hi please check this code.
useEffect(() => {
  const interval = setInterval(() => {
    console.log('This will be called every 2 seconds');
  }, 2000);

  return () => clearInterval(interval);
}, []);

Looking forward to your success.

**Comment by Oleksandr0811** [comment]
Okay Thanks 
Your code is working very well
